name: "deploy release"

on:
  release:
    types: [released]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: "Checkout"
      uses: actions/Checkout@v1
    - name: "Upload"
      uses: AnarkisGaming/workshop@v1
      with:
        appid: 108600
        publishedFileID: 3101379739
        path: src/Contents
        changelog: ${{ github.event.release.body }}
      env:
        STEAM_ACCOUNT_NAME: ${{ secrets.steamaccountname }}
        STEAM_PASSWORD: ${{ secrets.steampassword }}
