name: "Deploy to Workshop"

on:
  release:
    types: [released]

jobs:
  upload:
    runs-on: ubuntu-latest
    steps:
    - name: "Checkout"
      uses: actions/Checkout@v1
    - name: "Deploy"
      uses: AnarkisGaming/workshop@v1
      with:
        appid: 108600
        publishedFileID: 3101331450
        path: src
        changelog: ${{ github.event.release.body }}
      env:
        STEAM_ACCOUNT_NAME: ${{ secrets.steamaccountname }}
        STEAM_PASSWORD: ${{ secrets.steampassword }}
